services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_api
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/docker
    env_file:
      - ./backend/.env${APP_ENV:+-$APP_ENV}${ENV_FILE_SUFFIX:-}
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      - JWT_PASSPHRASE=80e75e1ceea2218d7be4a9d66df9d5b9752a069f337bbdcd97187991132d1ff3
      - DATABASE_URL=postgresql://user:password@database:5432/app_db
      - MERCURE_URL=http://caddy:9999/.well-known/mercure
      - MERCURE_PUBLIC_URL=${MERCURE_PUBLIC_URL}
      - MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    depends_on:
      - database
    networks:
      - app_network

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
      - "9999:9999"
      - "2019:2019"
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/frontend
      - ./caddy/Caddyfile${APP_ENV:+-$APP_ENV}${ENV_FILE_SUFFIX:-}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_certificates:/root/.local/share/caddy
    environment:
      - APP_ENV=${APP_ENV:-development}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      - MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      - MERCURE_PUBLIC_URL=${MERCURE_PUBLIC_URL}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_MERCURE_PUBLIC_URL=${VITE_MERCURE_PUBLIC_URL}
      - VITE_MERCURE_HOST=${VITE_MERCURE_HOST}
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${FRONTEND_TARGET:-development}
      args:
        - FRONTEND_TARGET=${FRONTEND_TARGET:-development}
    container_name: barbershop-frontend
    env_file:
      - ./frontend/.env${APP_ENV:+-$APP_ENV}${ENV_FILE_SUFFIX:-}
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_MERCURE_PUBLIC_URL=${VITE_MERCURE_PUBLIC_URL}
      - FRONTEND_TARGET=${FRONTEND_TARGET:-development}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - MERCURE_PUBLIC_URL=${MERCURE_PUBLIC_URL}
      - VITE_MERCURE_HOST=${VITE_MERCURE_HOST}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    networks:
      - app_network

  database:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app_network

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification_service
    volumes:
      - ./notification:/app:rw
      - notification_sessions:/app/sessions:rw
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE_NUMBER=${TELEGRAM_PHONE_NUMBER}
      - BARBERSHOP_NAME=${BARBERSHOP_NAME}
      - BARBERSHOP_MAPS_LINK=${BARBERSHOP_MAPS_LINK}
      - BARBERSHOP_PHONE=${BARBERSHOP_PHONE}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  caddy_certificates:
  notification_sessions:

networks:
  app_network:
    driver: bridge