version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_api
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/docker
    environment:
      - APP_ENV=dev
      - CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1|54\.37\.66\.72)(:[0-9]+)?$
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      - JWT_PASSPHRASE=80e75e1ceea2218d7be4a9d66df9d5b9752a069f337bbdcd97187991132d1ff3
      - DATABASE_URL=postgresql://user:password@database:5432/app_db
      - SYMFONY_DOTENV_VARS=CORS_ALLOW_ORIGIN
      - APP_RUNTIME_ENV=dev
    depends_on:
      - database
    networks:
      - app_network

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy_server
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./caddy/Caddyfile.caddy:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      target: ${FRONTEND_TARGET:-development}
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - NODE_ENV=${FRONTEND_TARGET:-development}

  database:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app_network

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification_service
    volumes:
      - ./notification:/app:rw
      - notification_sessions:/app/sessions:rw
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE_NUMBER=${TELEGRAM_PHONE_NUMBER}
      - BARBERSHOP_NAME=${BARBERSHOP_NAME}
      - BARBERSHOP_MAPS_LINK=${BARBERSHOP_MAPS_LINK}
      - BARBERSHOP_PHONE=${BARBERSHOP_PHONE}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend


  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
        anonymous
        subscriptions
    networks:
      - app_network
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile
    ports:
      - "9999:80"
    volumes:
      - ./backend:/var/www/html
      - ./caddy/Caddyfile.mercure:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  notification_sessions: