api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/DTO'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_swagger: true
    enable_swagger_ui: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    openapi:
        contact:
            name: API Support
            url: https://api-platform.com